--- #YAML:1.0
name:               Catalyst-Model-Bitcoin
version:            0.02
abstract:           Catalyst model class that interfaces 
author:
    - Pavel Karoukin <pavel@yepcorp.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:          5.8
    Finance::Bitcoin:  0.001
    Moose:             1.08
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
