--- #YAML:1.0
name:               Catalyst-Model-Bitcoin
version:            0.01
abstract:           Perl extension for blah blah blah
author:
    - Pavel Karoukin <pavel@yepcorp.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:  ~
    Moose:     Finance::Bitcoin
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
